### ISSUE TITLE
Typo in "attention" will prevent attention callbacks (and example) from working.

### ISSUE THREAD

**Issue by Psemaj** [Jor-G-ete/NeuroSkyPy#1]
https://github.com/Jor-G-ete/NeuroSkyPy/blob/145c52f92e8083d848bb547515c58f490dbf426e/NeuroSkyPy/NeuroSkyPy.py#L189

**Comment by dlevinson5** [comment]
Please fix.

**Comment by blrk** [comment]
Hi I am getting the following error. Appreciate your help 

Traceback (most recent call last):
  File "Nuero.py", line 16, in <module>
    neuropy.start()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\NeuroPy\NeuroPy.py", line 77, in start
    thread.start_new_thread(self.__packetParser,(self.srl,))
NameError: name 'thread' is not defined
